/* 
 * The MIT License
 *
 * Copyright 2014 David Jarski.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.davidjarski.javatzee.scorepad;

import javax.swing.BorderFactory;
import javax.swing.border.SoftBevelBorder;

public class ScorePanelLabels extends javax.swing.JPanel {
    
    /** Creates new form ScorePanelLabels */
    public ScorePanelLabels() {
        initComponents();
//        setBorder(BorderFactory.createCompoundBorder(
//                BorderFactory.createEmptyBorder(2, 0, 2, 0),
//                new SoftBevelBorder(SoftBevelBorder.RAISED)));        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        boxPanel = new javax.swing.JPanel();
        scoreBoxLabel1 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel2 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel3 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel4 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel5 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel6 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel7 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel8 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel9 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel10 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel11 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel12 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel13 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel14 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel15 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel16 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel17 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel18 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel19 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        scoreBoxLabel20 = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();
        grandTotalBox = new com.davidjarski.javatzee.scorepad.ScoreBoxLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(132, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(132, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(132, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        boxPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(227, 227, 227), new java.awt.Color(250, 250, 250), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        boxPanel.setLayout(new java.awt.GridBagLayout());

        scoreBoxLabel1.setText("Ones");
        scoreBoxLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel1, gridBagConstraints);

        scoreBoxLabel2.setText("Twos");
        scoreBoxLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel2, gridBagConstraints);

        scoreBoxLabel3.setText("Threes");
        scoreBoxLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel3, gridBagConstraints);

        scoreBoxLabel4.setText("Fours");
        scoreBoxLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel4, gridBagConstraints);

        scoreBoxLabel5.setText("Fives");
        scoreBoxLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel5, gridBagConstraints);

        scoreBoxLabel6.setText("Sixes");
        scoreBoxLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel6, gridBagConstraints);

        scoreBoxLabel7.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel7.setText("Upper Subtotal");
        scoreBoxLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel7, gridBagConstraints);

        scoreBoxLabel8.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel8.setText("Upper Bonus");
        scoreBoxLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel8, gridBagConstraints);

        scoreBoxLabel9.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel9.setText("Upper Total");
        scoreBoxLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel9, gridBagConstraints);

        scoreBoxLabel10.setText("Three of a Kind");
        scoreBoxLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel10, gridBagConstraints);

        scoreBoxLabel11.setText("Four of a Kind");
        scoreBoxLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel11, gridBagConstraints);

        scoreBoxLabel12.setText("Full House");
        scoreBoxLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel12, gridBagConstraints);

        scoreBoxLabel13.setText("Short Straight");
        scoreBoxLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel13, gridBagConstraints);

        scoreBoxLabel14.setText("Long Straight");
        scoreBoxLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel14, gridBagConstraints);

        scoreBoxLabel15.setText("Javatzee");
        scoreBoxLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel15, gridBagConstraints);

        scoreBoxLabel16.setText("Chance");
        scoreBoxLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel16, gridBagConstraints);

        scoreBoxLabel17.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel17.setText("Lower Total");
        scoreBoxLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel17, gridBagConstraints);

        scoreBoxLabel18.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel18.setText("Javatzee Bonus");
        scoreBoxLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel18, gridBagConstraints);

        scoreBoxLabel19.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel19.setText("Combined Total");
        scoreBoxLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel19, gridBagConstraints);

        scoreBoxLabel20.setBackground(new java.awt.Color(255, 228, 130));
        scoreBoxLabel20.setText("Multiplied Total");
        scoreBoxLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        boxPanel.add(scoreBoxLabel20, gridBagConstraints);

        grandTotalBox.setBackground(new java.awt.Color(153, 199, 127));
        grandTotalBox.setText("Grand Total");
        grandTotalBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        grandTotalBox.setMinimumSize(new java.awt.Dimension(125, 52));
        grandTotalBox.setPreferredSize(new java.awt.Dimension(125, 52));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 0, 1);
        boxPanel.add(grandTotalBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(boxPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPanel;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel grandTotalBox;
    private javax.swing.JLabel jLabel1;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel1;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel10;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel11;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel12;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel13;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel14;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel15;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel16;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel17;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel18;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel19;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel2;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel20;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel3;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel4;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel5;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel6;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel7;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel8;
    private com.davidjarski.javatzee.scorepad.ScoreBoxLabel scoreBoxLabel9;
    // End of variables declaration//GEN-END:variables
    
}
