/* 
 * The MIT License
 *
 * Copyright 2014 David Jarski.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.davidjarski.javatzee.help;

import com.davidjarski.javatzee.IO.IO;
import com.davidjarski.javatzee.IO.Resources;
import java.awt.Dimension;
import java.awt.Point;
import java.io.File;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class AboutDialog extends javax.swing.JDialog
{
    private static final String ABOUT =
"<html>" +
"<p><b><font size=+2>Triple Javatzee 0.8</font></b></p>" +
"<p>A dice game for the Java&#0153; platform</p>" +
"<br>" +
"<p>&copy; 2014 David B. Jarski</p>" +
"<p>This program is released under the MIT License.</p>" +
"</html>";
    
    private static final String DOUBLE_J =
"<html>" +
"<p>Revenna 3D Iconset used for toolbar is from </p>" +
"<p>Double-J Design at http://www.doublejdesign.co.uk</p>" +
"<p>and is used under the Creative Commons 3.0 Attribution license.</p>" +
"</html>";
    
    private static String license;
    private static final Dimension MIN_SIZE = new Dimension(400, 100);
    private static final int MIN_WIDTH = 400;
    private static final String TITLE = "About";
    
    /**
     * Creates new form NewJDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle(TITLE);
        lblIcon.setIcon(new ImageIcon(getClass().getResource(Resources.ABOUT_ICON_PATH)));
        lblAbout.setText(ABOUT);
        lblDoubleJ.setText(DOUBLE_J);
        txtLicense.setVisible(false);
        Dimension dimension = new Dimension(600, 0);
        pack();
        Point p = parent.getLocation();
        int xOffset = (parent.getWidth() - getWidth()) / 2;
        setLocation(p.x + xOffset, p.y + 50);
    }
    
    public Dimension getMinimumSize() {
        return MIN_SIZE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtLicense = new javax.swing.JTextArea();
        lblDoubleJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        iconPanel.add(lblIcon);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        mainPanel.add(iconPanel, gridBagConstraints);

        lblAbout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblAbout.setText("About");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        mainPanel.add(lblAbout, gridBagConstraints);

        jToggleButton1.setText("Show License");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(13, 30, 8, 0);
        mainPanel.add(jToggleButton1, gridBagConstraints);

        txtLicense.setEditable(false);
        txtLicense.setColumns(20);
        txtLicense.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtLicense.setRows(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(txtLicense, gridBagConstraints);

        lblDoubleJ.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDoubleJ.setText("Double J Design Attribution");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 30, 0, 0);
        mainPanel.add(lblDoubleJ, gridBagConstraints);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (txtLicense.isVisible()) {
            txtLicense.setVisible(false);
            pack();
        } else {
            if (license == null) {
                try {
                    File file;
                    file = new File(getClass().getResource(Resources.LICENSE_PATH).toURI());
                    license = IO.readTextFile(file);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            txtLicense.setText(license);
            txtLicense.setVisible(true);
            pack();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel iconPanel;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblDoubleJ;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea txtLicense;
    // End of variables declaration//GEN-END:variables
}
